# Generated by Django 4.2.3 on 2024-07-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitepathapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
