# Generated by Django 4.2.3 on 2024-07-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitepathapp', '0003_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
